language: python
install:
  - pip install mkdocs-material
  - pip install mike
jobs:
  include:
    - stage: build master
      script: mike deploy
    if: branch = master OR type = pull_request
    - stage: release docs
      if: branch =~ /release/
      script: mike deploy ${TRAVIS_BRANCH#'release/'} --push
