language: python
install:
  - pip install mkdocs-material
  - pip install mike
  - mike install-extras
deploy:
  script: mike deploy ${TRAVIS_BRANCH#'release/'}
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site
  on:
    branch: ${TRAVIS_BRANCH#'release/'}


